### PR TITLE
Show old/new leaderboard position on pb

### PR DESCRIPTION
**Pull request by Pigalala**
Show old and new leaderboard position on new PB.

Modifies `messages.timer.firstFinish` and `messages.timer.newRecord`:
```
messages:
  timer:
    firstFinish: '&eNew best time!&6 You finished &e%map%&6 in &e%time%&6. (&e#- &6→ &e#%position%&6)'
    newRecord: '&eNew best time!&6 You finished &e%map%&6 in &e%time%&6. Your previous best was &e%oldTime%&6. (&e#%oldposition% &6→ &e#%newposition%&6)'
```

### CODE REVIEW

**Comment by Makkuusen** [comment]
I wanna know if you could just put the jar file in and the language files would update, or if you have to manually update the language files or remove them upon upgrade. If you don't know, feel free to just send me the jar and I'll test it out.

If it needs manual work, I think we need to solve that before adding it. Either by hardcoding the text in code, or by automatically update language files. But I think the last option might be waste of time if the system will be replaced in the future.

**Comment by Pigalala** [comment]
I'm 99% sure that the lang files don't update automatically. 
I think the best solution is to get people to manually update their lang files or we could completely skip using a lang file for this. This means that we don't have to bother with making a system right now and it should avoid interfierence with modified lang files.

**Comment by Makkuusen** [comment]
Could you change it to be a player.sendMessage() instead of using lang files? And I'll merge it after that!

**Comment by Pigalala** [comment]
This still uses the lang file but doesn't modify it

**Pull request merged**
